- resources/views/index.blade.php
> [initial-setup/index]

- resources/views/footer.blade.php
Changes:
- Added footer layout code initially
> initial-setup/footer - Modified footer.blade.php

- resources/views/what-is-bmi.blade.php
Added default code into the what-is-bmi.blade.php
> initial-setup/what-is-bmi - modify what-is-bmi.blade.php

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/HomeController.php
- resources/views/index.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
- Editted route for index.blade.php
- Editted head of app.blade.php
- Included 2 pages in index.blade.php
- Editted 3 controllers
> [initial-setup/route] - Landing Page Changes

- public/css/register.css
- public/css/style.css
- resources/views/auth/register.blade.php
-created new CSS file
-moved code CSS to new CSS file
> [UI/register] -Modified

- database/migrations/0001_01_01_000000_create_users_table.php
- resources/views/auth/register.blade.php
- Created migration for users table
- Added "@section('title', 'Register')" to register.blade
> [migration/users] - created migration for users table

- public/css/index-page.css
- resources/views/index.blade.php
- resources/views/what-is-bmi.blade.php
- add "what-is-bmi"part to index.blade
> [UI/index] - add "what-is-bmi"part to index.blade

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/HomeController.php
- app/Models/User.php
- database/migrations/0001_01_01_000000_create_users_table.php
- public/css/style.css
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- resources/views/footer.blade.php
- resources/views/layouts/app.blade.php
- resources/views/weight_and_meals/weight_and_meals.blade.php
- routes/web.php
- modified migration for users table
- modified User model
- modified Register and Login Controllers
- modified some blade pages (register, login, layout/app)
- made a new route for landing page (weight-and-meals.blade) after logging in
> [Backend/register] - Backend for pages before logging in

- app/Http/Controllers/HomeController.php
- public/css/Profile/profile-allmeals-posts.css
- public/css/Profile/profile-edit.css
- public/css/Profile/profile-logweight-history.css
- public/css/Profile/profile.css
- public/css/style.css
- resources/views/layouts/app.blade.php
- resources/views/profile/all-meal-posts.blade.php
- resources/views/profile/logweight-history.blade.php
- resources/views/profile/modals/delete-account.blade.php
- resources/views/profile/modals/delete-weight-log.blade.php
- resources/views/profile/modals/edit-weight-log.blade.php
- resources/views/profile/profile-edit.blade.php
- resources/views/profile/profile-main.blade.php
Additions
-Changed style.css
-Changed app.blade
-Changed profile-main
-Changed profile-edit
-Changed profile.css
-Changed profile-edit.css
-Changed  modal for delete account
-Added  profile/log-weight-history
-Added  profile/all-meal-posts
-Added profile/log-weight-history css
-Added  profile/all-meal-posts css
-Added modal for delete-weight-log
-Added modal for edit-weight-log
-Added just for now / HomeContoller
> [UI/Profile]  Profile page UI

- app/Http/Controllers/Admin/CommunitiesController.php
- app/Models/Community.php
- database/migrations/2024_05_28_124030_create_communities_table.php
- database/seeders/CommunitySeeder.php
- database/seeders/DatabaseSeeder.php
- public/css/style.css
- resources/views/admin/communities/index.blade.php
- resources/views/admin/communities/modal/action.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
- Frontend for admin's community control page
- Backend for admin's community control page
- Created CommunitySeeder to set 8 communities by default
> [UI/admin/communities] - created admin's community control page

- app/Http/Controllers/HomeController.php
- app/Models/Community.php
- database/migrations/2024_05_25_052014_create_communities_table.php
- public/css/community-top.css
- resources/views/community/community-top.blade.php
[UI/community-top]  -Modified
[Backend/Community,communities_table,HomeController,Community.php]　-Modified,Created
Modified
-Modified community-top
-Modified HomeController
Created
-Created Community.php
-Created communities_table
> [UI/community-top]

- app/Http/Controllers/CalendarController.php
- app/Http/Controllers/ChartController.php
- app/Http/Controllers/HomeController.php
- resources/views/layouts/app.blade.php
- resources/views/weight_and_meals/weight_and_meals.blade.php
- routes/web.php
-made weight and meals table
-made some changes
> [Backend/weight&meals] -updated some code

- app/Http/Controllers/MealController.php
- app/Http/Controllers/WeightController.php
- app/Models/Meal.php
- app/Models/User.php
- app/Models/Weight.php
- database/migrations/2024_05_31_113823_create_meals_table.php
- public/css/calendar.css
- resources/views/layouts/app.blade.php
- resources/views/weight_and_meals/modals/meals_delete.blade.php
- resources/views/weight_and_meals/modals/post_meals.blade.php
- resources/views/weight_and_meals/modals/record.blade.php
- routes/web.php
-made model and controller for weight record
-made model and controller for post meals
> [Backend/weight&meals] -made controller

- app/Http/Controllers/CalendarController.php
- app/Http/Controllers/HomeController.php
- app/Http/Controllers/MealController.php
- app/Models/User.php
- package-lock.json
- package.json
- public/css/calendar.css
- public/css/chart.css
- public/css/weight-and-meals.css
- resources/views/weight_and_meals/modals/meals_delete.blade.php
- resources/views/weight_and_meals/weight_and_meals.blade.php
- routes/web.php
-display latest image
-added some code to controller, modal and CSS
> [Backend/weight&meals] - insert code to display image

- public/js/chart.js
- resources/views/weight_and_meals/weight_and_meals.blade.php
> [Backend/weight&meals] made some changes

- app/Http/Controllers/Admin/PostsController.php
- app/Models/Community.php
- database/seeders/DatabaseSeeder.php
- public/css/admin/posts.css
- resources/views/admin/communities/index.blade.php
- resources/views/admin/posts/index.blade.php
- resources/views/admin/posts/modal/action.blade.php
- resources/views/admin/posts/modal/status.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
- Frontend of the page
- Backend of the page
- some small fixation of other admin pages.
> [UI/admin/posts] - created admin's post control page

- app/Http/Controllers/WeightController.php
- resources/views/profile/logweight-history.blade.php
Changed logweight-history.blade.php
> [Backend/bugfix]

- resources/views/community/community-all-posts.blade.php
- resources/views/profile/all-your-posts.blade.php
- resources/views/profile/logweight-history.blade.php
- resources/views/weight_and_meals/modals/post_meals.blade.php
- display number of comments and likes
- some bug fixed
> [adjustment] - some adjustment

- app/Http/Controllers/CalendarController.php
- resources/views/weight_and_meals/weight_and_meals.blade.php
- routes/web.php
-fixes some bugs for calendar area
> [Backend/weight&meals] -fixed some bugs

- public/js/selected_date.js
> [Backend/weight&meals] -edited delected_date.js
